#!/usr/bin/env bash
# Script to modify the hosts file to change localhost and facebook.com resolution

# Check if the script is run as root (needed to edit /etc/hosts)
cp /etc/hosts ~/hosts.new
sed -i 's/^127.0.0.1.*/127.0.0.2 localhost/g' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
