#!/usr/bin/env bash
# Script to modify the hosts file to change localhost and facebook.com resolution

# Check if the script is run as root (needed to edit /etc/hosts)
if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root! Use sudo."
    exit 1
fi

# Modify the /etc/hosts file to change IP resolution
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
